### ISSUE TITLE
Unable to build using meson

### ISSUE THREAD

**Issue by guptadhaval18** [SUSE/phoebe#29] opened 2021-03-10 13:17 UTC
I am trying to build using meson as given in readme. But after I execute third line it gives error 
![image](https://user-images.githubusercontent.com/47078156/110634682-4114e080-81d0-11eb-945e-c572b794878a.png)

Please see if it same for others .

**Comment by mvarlese** [comment] 2021-03-10 13:20
Well obviously not, considered the CI/CD we have here is successfully building and running the code.
That said we did not spend anytime trying to build (nor run) the code on an Ubuntu installation. 

A PR (if required) to fix the issue you see would be very much welcome tho!

**Comment by dcermak** [comment] 2021-03-10 13:39
@guptadhaval18 either do: `meson build && meson compile -C build` or `meson build && cd build && ninja`.

EDIT: I just tried it on my machine with meson 0.55.3 and there the instructions work. So my guess is that meson 0.53 might not support `meson compile` as we outline it. Could you check if either of the two other methods work for you?

**Comment by mukul-mehta** [comment] 2021-03-12 20:02
I believe it could be an issue since `pkg-config` seems to be an old version for you. I tried setting up on a new Tumbleweed VM today and it worked alright for me. This is the output of `meson build` for me

![image](https://user-images.githubusercontent.com/43145555/110992375-da442280-839b-11eb-868a-8be826722dc5.png)

**Comment by dcermak** [comment] 2021-03-13 21:52
@mukul-mehta It is highly unlikely that this is caused by `pkg-config`, as that is only used to discover dependencies by meson and not to actually compile anything.

@guptadhaval18 Can you compile phoeβe by using ninja directly?

**Comment by mvarlese** [comment] 2021-03-14 15:21
> I believe it could be an issue since `pkg-config` seems to be an old version for you. I tried setting up on a new Tumbleweed VM today and it worked alright for me. This is the output of `meson build` for me
> 
> ![image](https://user-images.githubusercontent.com/43145555/110992375-da442280-839b-11eb-868a-8be826722dc5.png)

I'm confused now: is the code building or not for yourself?

**Comment by mukul-mehta** [comment] 2021-03-14 16:11
@mvarlese The code builds successfully for me. I was able to run `meson build` and `meson compile` and run the code in both training and inference modes

**Comment by mvarlese** [comment] 2021-03-15 07:23
@mukul-mehta then I believe we can close this issue.

**Closed as completed by mvarlese** 2021-03-15 07:23 UTC
